RegistrationAndLogin2/Models/Enroll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace RegistrationAndLogin2.Models
{
    public class Enroll
    {
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "FirstName(이름)을 입력해주세요.")]
        [Display(Name = "FirstName")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "LastName(성)을 입력해주세요.")]
        [Display(Name = "LastName")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "비밀번호를 입력해주세요.")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "Password \"{0}\" must have {2} character", MinimumLength = 8)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{6,}$", ErrorMessage = "비빌번호는 최소 8자(대소문자, 숫자, 특수기호 최소 각각 1자)가 필요합니다.")]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        [Required(ErrorMessage = "비밀번호를 다시 입력해주세요.")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "비밀번호가 일치하지 않습니다. 다시 시도해주세요!")]
        [DataType(DataType.Password)]
        public string Confirmpwd { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }

        public string Gender { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail 형식이 올바르지 않습니다.")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "전화번호를 입력해주세요")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$", ErrorMessage = "전화번호 형식(숫자 8자리)이 올바르지 않습니다.")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "보안질문을 입력해주세요.")]
        [Display(Name = "보안질문")]
        public string SecurityAnwser { get; set; }

        public List<Enroll> Enrollsinfo { get; set; }

    }
}

RegistrationAndLogin2/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegistrationAndLogin2.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace RegistrationAndLogin2.Controllers
{
    public class EnrollmentController : Controller
    {
        public string value = "";

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Enroll e)
        {
            if (Request.HttpMethod == "POST")
            {
                Enroll er = new Enroll();
                using (SqlConnection con = new SqlConnection("Server=localhost;User=test;Password=1234;Database=test;"))
                {
                    using (SqlCommand cmd = new SqlCommand("SP_EnrollDetail", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@FirstName", e.FirstName);
                        cmd.Parameters.AddWithValue("@LastName", e.LastName);
                        cmd.Parameters.AddWithValue("@Password", e.Password);
                        cmd.Parameters.AddWithValue("@Gender", e.Gender);
                        cmd.Parameters.AddWithValue("@Email", e.Email);
                        cmd.Parameters.AddWithValue("@Phone", e.PhoneNumber);
                        cmd.Parameters.AddWithValue("@SecurityAnwser", e.SecurityAnwser);
                        cmd.Parameters.AddWithValue("@status", "INSERT");
                        con.Open();
                        ViewData["result"] = cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }
            }
            return View();
        }
    }
}

RegistrationAndLogin2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistrationAndLogin2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RegistrationAndLogin2/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegistrationAndLogin2.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Web.Security;

namespace RegistrationAndLogin2.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: /UserLogin/  
        public string status;

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Enroll e)
        {
            String SqlCon = ConfigurationManager.ConnectionStrings["ConnDB"].ConnectionString;
            SqlConnection con = new SqlConnection(SqlCon);
            string SqlQuery = "select Email,Password from Enrollment where Email=@Email and Password=@Password";
            con.Open();
            SqlCommand cmd = new SqlCommand(SqlQuery, con); ;
            cmd.Parameters.AddWithValue("@Email", e.Email);
            cmd.Parameters.AddWithValue("@Password", e.Password);
            SqlDataReader sdr = cmd.ExecuteReader();
            if (sdr.Read())
            {
                Session["Email"] = e.Email.ToString();
                return RedirectToAction("Welcome");
            }
            else
            {
                ViewData["Message"] = "User Login Details Failed!!";
            }
            if (e.Email.ToString() != null)
            {
                Session["Email"] = e.Email.ToString();
                status = "1";
            }
            else
            {
                status = "3";
            }
            con.Close();
            return View();
            //return new JsonResult { Data = new { status = status } };  
        }

        [HttpGet]
        public ActionResult Welcome(Enroll e)
        {
            Enroll user = new Enroll();
            DataSet ds = new DataSet();

            using (SqlConnection con = new SqlConnection("Server=localhost;User=test;Password=1234;Database=test;"))
            {
                using (SqlCommand cmd = new SqlCommand("sp_GetEnrollmentDetails", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@Email", SqlDbType.VarChar, 30).Value = Session["Email"].ToString();
                    con.Open();
                    SqlDataAdapter sda = new SqlDataAdapter(cmd);
                    sda.Fill(ds);
                    List<Enroll> userlist = new List<Enroll>();
                    for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                    {
                        Enroll uobj = new Enroll();
                        uobj.ID = Convert.ToInt32(ds.Tables[0].Rows[i]["ID"].ToString());
                        uobj.FirstName = ds.Tables[0].Rows[i]["FirstName"].ToString();
                        uobj.LastName = ds.Tables[0].Rows[i]["LastName"].ToString();
                        uobj.Password = ds.Tables[0].Rows[i]["Password"].ToString();
                        uobj.Email = ds.Tables[0].Rows[i]["Email"].ToString();
                        uobj.PhoneNumber = ds.Tables[0].Rows[i]["Phone"].ToString();
                        uobj.SecurityAnwser = ds.Tables[0].Rows[i]["SecurityAnwser"].ToString();
                        uobj.Gender = ds.Tables[0].Rows[i]["Gender"].ToString();

                        userlist.Add(uobj);
                    }
                    user.Enrollsinfo = userlist;
                }
                con.Close();

            }
            return View(user);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); //세션 파괴. 사용자가 사이트를 떠날 것이 확실하다면 Session.Abandon을 사용.
            return RedirectToAction("Index", "UserLogin");
        }
    }
}

RegistrationAndLogin2/Views/Enrollment/Index.cshtml
@model RegistrationAndLogin2.Models.Enroll

@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>회원가입</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="../../Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Scripts/jquery-1.7.1.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/Scripts/passwordscheck.js"></script>
    <link href="~/Scripts/passwordscheck.css" rel="stylesheet" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
</head>
<body>
    <!------ Include the above in your HEAD tag ---------->
    @using (Html.BeginForm("Index", "Enrollment", FormMethod.Post))
    {
        <div class="container register">
            <div class="row">
                <div class="col-md-3 register-left">
                    <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
                    <h1>환영합니다.</h1>
                    <p>누구나 쉽게 시작할 수 있는 SNS판매의 시작 스룩페이!</p>
                </div>
                <div class="col-md-9 register-right">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="../UserLogin/Index" role="tab" aria-controls="profile" aria-selected="false">로그인</a>
                        </li>
                    </ul>
                    <pre>

                    </pre>
                    <hr />
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">회원가입</h3>
                            <div class="row register-form">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.FirstName, new { @class = "form-control", placeholder = "First Name(이름) *" })
                                        @Html.ValidationMessageFor(e => e.FirstName)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.LastName, new { @class = "form-control", placeholder = "Last Name(성) *" })
                                        @Html.ValidationMessageFor(e => e.LastName)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Password, new { id = "password", @class = "form-control", placeholder = "비밀번호 *" })
                                        <span id="result"></span>
                                        @Html.ValidationMessageFor(e => e.Password)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Confirmpwd, new { @class = "form-control", placeholder = "비밀번호 확인 *" })
                                        @Html.ValidationMessageFor(e => e.Confirmpwd)
                                    </div>
                                    <div class="form-group">
                                        <div class="maxl">
                                            @Html.RadioButtonFor(e => e.Gender, "Male", new { @class = "radio inline" })<span>남성</span>
                                            @Html.RadioButtonFor(e => e.Gender, "Female", new { @class = "radio inline" })<span>여성</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.Email, new { @class = "form-control", placeholder = "Email *" })
                                        @Html.ValidationMessageFor(e => e.Email)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.PhoneNumber, new { @class = "form-control", placeholder = "전화번호 *" })
                                        @Html.ValidationMessageFor(e => e.PhoneNumber)

                                    </div>
                                    <div class="form-group">
                                        <select class="form-control">
                                            <option class="hidden" selected disabled>보안질문을 선택하세요.</option>
                                            <option>나의 생년월일은? (ex. 950808)</option>
                                            <option>어머니 성함은?</option>
                                            <option>출신 초등학교는?</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.SecurityAnwser, new { @class = "form-control", placeholder = "답변 *" })
                                        @Html.ValidationMessageFor(e => e.SecurityAnwser)

                                    </div>
                                    <input type="submit" class="btnRegister" value="등록" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                $(function () {
                    var msg = '@ViewData["result"]';
                    if (msg == '1')
                    {
                        alert("회원가입이 성공적으로 완료되었습니다.");
                        window.location.href = "@Url.Action("Index", "Enrollment")";
                    }
                });
            </script>
        </div>
    }
</body>
</html>    

RegistrationAndLogin2/Views/UserLogin/Index.cshtml
@model RegistrationAndLogin2.Models.Enroll

@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>로그인</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="../../Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">

    $(document).ready(function () {
        $.ajax({
            type: 'POST',
            URL: '/UserLogin/UserLogin',
            data: data,
            dataType: 'JSON',
            success: function (data) {
                datadata = data.status
                if (status == "1") {
                    window.location.href = '@Url.Action("Index","UserLogin")';
                }
            }
        });
    });
    </script>
</head>

<body>
    <!------ Include the above in your HEAD tag ---------->
    @using (Html.BeginForm("Index", "UserLogin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container register">
            <div class="row">
                <div class="col-md-3 register-left">
                    <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
                    <h1>환영합니다.</h1>
                    <p>누구나 쉽게 시작할 수 있는 SNS판매의 시작 스룩페이!</p>
                </div>
                <div class="col-md-9 register-right">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="../Enrollment/Index" role="tab" aria-controls="home" aria-selected="true">회원가입</a>
                        </li>
                    </ul>
                    <pre>

                    </pre>
                    <hr />
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">로그인</h3>
                            <div class="row register-form">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.Email, new { @class = "form-control", placeholder = "Email" })
                                        @Html.ValidationMessageFor(e => e.Email)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Password, new { id = "password", @class = "form-control", placeholder = "비밀번호" })
                                        <span id="result"></span>
                                        @Html.ValidationMessageFor(e => e.Password)
                                    </div>
                                    <div class="col-md-6">
                                        <input type="submit" class="btnLogin" value="로그인" />
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
               $(function () {
                     var msg = '@ViewData["result"]';
                     if (msg == '1')
                     {
                         alert("안녕하세요. 환영합니다!");
                         window.location.href = "@Url.Action("Index", "UserLogin")";
                     }
                  });
            </script>
        </div>
    }
</body>
</html>    

RegistrationAndLogin2/Views/UserLogin/Welcome.cshtml
@model RegistrationAndLogin2.Models.Enroll

@{
    ViewBag.Title = "Welcome";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>FREE RESPONSIVE HORIZONTAL ADMIN</title>
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="../../Content/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONT AWESOME STYLE  -->
    <link href="../../Content/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="../../Content/assets/css/style.css" rel="stylesheet" />
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>
<body>
    <div class="navbar navbar-inverse set-radius-zero">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="Welcome">
                    <img src="../../Content/assets/img/logo.png" width="60"/>
                </a>
            </div>
            <div class="right-div">
                @Html.ActionLink("로그아웃", "Logout", "UserLogin", new { @class = "btn btn-danger pull-right" })
            </div>
        </div>
    </div>
    <!-- LOGO HEADER END-->
    <section class="menu-section">
        <div class="container">
            <div class="row ">
                <div class="col-md-12">
                    <div class="navbar-collapse collapse ">
                        <ul id="menu-top" class="nav navbar-nav navbar-right">
                            <li><a href="welcome" class="menu-top-active">DASHBOARD</a></li>
                            @if (Session["Email"] != null)
                            {
                                <li><a href="welcome" class="menu-top-active">Welcome @Session["Email"].ToString()</a></li>
                            }
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <pre>

    </pre>
    <hr />
    <!-- MENU SECTION END-->
    <div class="content-wrapper">
        <div class="container">
            <div class="row pad-botm">
                <div class="col-md-12">
                    <h4 class="header-line">ADMIN DASHBOARD</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div id="carousel-example" class="carousel slide slide-bdr" data-ride="carousel">

                        <div class="carousel-inner">
                            <div class="item active">

                                <img src="../../Content/assets/img/1.jpg" alt="" />

                            </div>
                            <div class="item">
                                <img src="../../Content/assets/img/2.jpg" alt="" />

                            </div>
                            <div class="item">
                                <img src="../../Content/assets/img/3.jpg" alt="" />

                            </div>
                        </div>
                        <!--INDICATORS-->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example" data-slide-to="1"></li>
                            <li data-target="#carousel-example" data-slide-to="2"></li>
                        </ol>
                        <!--PREVIUS-NEXT BUTTONS-->
                        <a class="left carousel-control" href="#carousel-example" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div>
            <pre>

            </pre>
            <hr />
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            회원정보
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                @if (Model != null)
                                {
                                    if (Model.Enrollsinfo.Count > 0)
                                    {
                                        <table class="table table-striped table-bordered table-hover">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>ID</th>
                                                    <th>FirstName(이름)</th>
                                                    <th>LastName(성)</th>
                                                    <th>비밀번호</th>
                                                    <th>Email</th>
                                                    <th>전화번호</th>
                                                    <th>보안질문 답변</th>
                                                    <th>성별</th>
                                                </tr>
                                                @foreach (var item in Model.Enrollsinfo)
                                                {
                                                    <tr>
                                                        <td></td>
                                                        <td>@Html.DisplayFor(modelitem => item.ID) </td>
                                                        <td>@Html.DisplayFor(modelitem => item.FirstName)</td>
                                                        <td>@Html.DisplayFor(modelitem => item.LastName)</td>
                                                        <td>@Html.DisplayFor(modelitem => item.Password)</td>
                                                        <td>@Html.DisplayFor(modelitem => item.Email) </td>
                                                        <td>@Html.DisplayFor(modelitem => item.PhoneNumber)</td>
                                                        <td>@Html.DisplayFor(modelitem => item.SecurityAnwser)</td>
                                                        <td>@Html.DisplayFor(modelitem => item.Gender)</td>
                                                    </tr>
                                                }
                                            </thead>
                                        </table>
                                    }
                                    else
                                    {
                                        <b>No Details Found.</b>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- CONTENT-WRAPPER SECTION END-->
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    Copyright ⓒ Srook Co., Ltd. All Rights Reserved | <a href="https://srookpay.com/" target="_blank"> © 2022 (주)스룩</a>
                </div>

            </div>
        </div>
    </section>
    <!-- FOOTER SECTION END-->
    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY  -->
    <script src="../../Content/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="../../Content/assets/js/bootstrap.js"></script>
    <!-- CUSTOM SCRIPTS  -->
    <script src="../../Content/assets/js/custom.js"></script>
</body>
</html>    